spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev   # 开发环境
  application:
    name: microservicecloud-config-liuxin-dev
---
spring:
  profiles: test   # 测试环境
  application:
    name: microservicecloud-config-liuxin-test
# 文件的保存形式是UTF-8  ---是分隔符的意思