spring:
  profiles:
   active:
   - dev
---
server:
    prot: 8001  #注册中心占用7001端口，冒号后面必须要有空格
spring: 
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01  #数据库名称
    username: root
    password: liuxin18
    dbcp2:
      min-idle: 5    #数据库连接池的最小维持链接数
      initial-size: 5 #初始化连接数
      max-total: 5      #最大连接数
      max-wait-millis: 20 #等待链接获取的最大超时时间 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所路劲，在当前工程resouces文件下新建mybatis文件夹以及mybatis文件下新建xml文件
  type-aliases-package: com.liuxin.springcloud.entities #所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper映射文件
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka  #注册
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id:  microservicecloud-dept8001  #显示名称
    prefer-ip-address: true   #访问路径的IP地址显示
    
info:
  app.name: liuxin-micorservice-cloud
  company.name: www.xinxin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$         